### ISSUE TITLE
Not support Ruby 3.x

### ISSUE THREAD

**Issue by ralphsun73221** [NomadThanatos/readmoo-dl#5]
我在使用的時候回一直出現如下的錯誤訊息

C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/firefox.rb:22:in `require': cannot load such file -- rexml/document (LoadError)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/firefox.rb:22:in `<top (required)>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/webdrivers-4.6.1/lib/webdrivers/geckodriver.rb:72:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/webdrivers-4.6.1/lib/webdrivers/geckodriver.rb:72:in `<top (required)>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/webdrivers-4.6.1/lib/webdrivers.rb:4:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/webdrivers-4.6.1/lib/webdrivers.rb:4:in `<top (required)>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:60:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:55:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:55:in `block in require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:44:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:44:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler.rb:175:in `require'
        from D:/OneDrive/桌面/readmoo-dl-master/lib/readmoo_dl.rb:3:in `<top (required)>'
        from main.rb:1:in `require_relative'
        from main.rb:1:in `<main>'

不知道原因是什麼

**Comment by NomadThanatos** [comment]
Hi, thanks for you report.
Since I do not use Firefox, I do not have a way to reproduce this.

But in searching around this issue, it seems that Firefox need rexml as dependency.
So you can try to run `gem install rexml` to see if it is fixed.

If so, we can add `gem rexml` into [Gemfile](https://github.com/NomadThanatos/readmoo-dl/blob/master/Gemfile) as Firefox dependency

**Comment by ralphsun73221** [comment]
> Hi, thanks for you report. Since I do not use Firefox, I do not have a way to reproduce this.
> 
> But in searching around this issue, it seems that Firefox need rexml as dependency. So you can try to run `gem install rexml` to see if it is fixed.
> 
> If so, we can add `gem rexml` into [Gemfile](https://github.com/NomadThanatos/readmoo-dl/blob/master/Gemfile) as Firefox dependency

安裝完，也把 rexml 加入了 Gemfile 裡面，結果出現這個錯誤

正在取得檔案路徑...C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/firefox/driver.rb:31:in `new': wrong number of arguments (given 1, expected 0) (ArgumentError)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:54:in `for'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver.rb:88:in `for'
        from D:/OneDrive/桌面/readmoo-dl-master/lib/readmoo_dl/API.rb:43:in `login'
        from D:/OneDrive/桌面/readmoo-dl-master/lib/readmoo_dl/API.rb:9:in `fetch'
        from D:/OneDrive/桌面/readmoo-dl-master/lib/readmoo_dl/downloader.rb:43:in `fetch_base_file'
        from D:/OneDrive/桌面/readmoo-dl-master/lib/readmoo_dl/downloader.rb:24:in `block in download'
        from D:/OneDrive/桌面/readmoo-dl-master/lib/readmoo_dl/downloader.rb:38:in `job'
        from D:/OneDrive/桌面/readmoo-dl-master/lib/readmoo_dl/downloader.rb:24:in `download'
        from main.rb:19:in `<main>'

**Comment by NomadThanatos** [comment]
This is weird.
Can you confirm your changes to firefox should be exact same as below in [here](https://github.com/NomadThanatos/readmoo-dl/blob/master/lib/readmoo_dl/API.rb#L43)
`driver = Selenium::WebDriver.for :firefox`

Your logs show that it passes 1 argument and it is expected to be 0, but I do not see any argument here.

Reference: https://www.selenium.dev/documentation/#tabs-1-3

**Comment by NomadThanatos** [comment]
Ok I find another related [issue](https://github.com/SeleniumHQ/selenium/issues/9119).
Can you try to run it with ruby 2.6?

**Comment by NomadThanatos** [comment]
And I think this dependency issue is also cause by ruby 3.0.
https://github.com/SeleniumHQ/selenium/pull/9007

**Comment by ralphsun73221** [comment]
> Ok I find another related issue: [SeleniumHQ/selenium#9119](https://github.com/SeleniumHQ/selenium/issues/9119)
> Can you try to run it with ruby 2.x , x > 4?

是 Ruby 的版本問題沒有錯，我使用 2.7.5 就可以成功執行了。

謝謝！
